#!/usr/bin/env python3
"""
Generate optimized QA_LOOKUP table from knowledge_base_qa.md
Extracts all 120 Q&A pairs and creates multiple matching keywords per question
"""

import re

def parse_knowledge_base(filepath):
    """Parse knowledge_base_qa.md and extract Q&A pairs"""
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Split by --- separator
    entries = content.split('---\n')
    
    qa_pairs = []
    for entry in entries:
        entry = entry.strip()
        if not entry:
            continue
        
        # Match Q: and Answer pattern
        match = re.match(r'### Q:\s*(.+?)\n\n\*\*Ответ:\*\*\s*(.+)', entry, re.DOTALL)
        if match:
            question = match.group(1).strip()
            answer = match.group(2).strip()
            qa_pairs.append((question, answer))
    
    return qa_pairs

def extract_keywords(question):
    """Extract multiple keywords for fuzzy matching"""
    keywords = []
    
    # Remove question words and common particles
    stop_words = ['кто', 'что', 'какой', 'какая', 'какое', 'какие', 'сколько', 
                  'где', 'когда', 'почему', 'зачем', 'как', 'каков', 'какие',
                  'у', 'в', 'на', 'с', 'по', 'о', 'об', 'от', 'до', 'из',
                  'для', 'при', 'через', 'после', 'между', 'над', 'под',
                  'и', 'или', 'но', 'а', 'же', 'ли', 'бы', 'не', 'ни',
                  'это', 'тот', 'эта', 'это', 'эти', 'все', 'весь',
                  'самый', 'самая', 'самое', 'самые']
    
    # Convert to lowercase and split
    words = question.lower().split()
    
    # Filter out stop words and short words
    important_words = [w for w in words if w not in stop_words and len(w) > 2]
    
    # Add full question (lowercased)
    keywords.append(question.lower())
    
    # Add individual important words
    keywords.extend(important_words)
    
    # Add 2-3 word phrases
    for i in range(len(important_words) - 1):
        if i + 1 < len(important_words):
            keywords.append(f"{important_words[i]} {important_words[i+1]}")
    
    # Add stemmed versions (remove last 1-2 characters for matching)
    for word in important_words:
        if len(word) > 4:
            keywords.append(word[:-1])  # Remove last char
        if len(word) > 5:
            keywords.append(word[:-2])  # Remove last 2 chars
    
    # Remove duplicates while preserving order
    seen = set()
    unique_keywords = []
    for kw in keywords:
        if kw not in seen:
            seen.add(kw)
            unique_keywords.append(kw)
    
    return unique_keywords

def generate_c_lookup_code(qa_pairs):
    """Generate C code for QA_LOOKUP table"""
    
    print("/* ─── Auto-generated Q&A lookup from knowledge_base_qa.md ─── */")
    print("/* Generated by generate_qa_lookup.py - DO NOT EDIT MANUALLY */")
    print(f"/* Total entries: {len(qa_pairs)} */\n")
    
    print("static const char *QA_LOOKUP[][2] = {")
    
    for question, answer in qa_pairs:
        # Extract keywords
        keywords = extract_keywords(question)
        
        # Use first 2-3 best keywords for matching
        # Prioritize longer, more specific keywords
        best_keywords = sorted(keywords[1:], key=len, reverse=True)[:3]
        
        # Escape quotes in answer
        answer_escaped = answer.replace('"', '\\"')
        
        # Generate multiple entries for each keyword
        for kw in best_keywords:
            kw_escaped = kw.replace('"', '\\"')
            entry = '    {{"' + kw_escaped + '", "' + answer_escaped + '"}},'
            print(entry)
    
    print("    {NULL, NULL}")
    print("};")

def generate_improved_matcher(qa_pairs):
    """Generate improved matching function with normalization"""
    
    print("""
/* Improved Q&A matching with normalization and fuzzy matching */
static const char *find_qa_answer(const char *message) {
    if (!message || message[0] == '\\0')
        return NULL;
    
    /* Create lowercase copy for case-insensitive matching */
    char msg_lower[2048];
    int len = strlen(message);
    if (len >= 2048) len = 2047;
    
    for (int i = 0; i < len; i++) {
        char c = message[i];
        /* Simple ASCII lowercase conversion */
        if (c >= 'A' && c <= 'Z')
            msg_lower[i] = c + 32;
        else
            msg_lower[i] = c;
    }
    msg_lower[len] = '\\0';
    
    /* Remove question marks and extra punctuation for matching */
    char msg_clean[2048];
    int j = 0;
    for (int i = 0; i < len; i++) {
        char c = msg_lower[i];
        if (c != '?' && c != '!' && c != '.' && c != ',' && c != '"') {
            msg_clean[j++] = c;
        }
    }
    msg_clean[j] = '\\0';
    
    /* Phase 1: Try exact multi-word keyword matching */
    for (int i = 0; QA_LOOKUP[i][0]; i++) {
        const char *keyword = QA_LOOKUP[i][0];
        const char *answer = QA_LOOKUP[i][1];
        
        /* Case-insensitive substring match */
        if (strstr(msg_clean, keyword)) {
            return answer;
        }
    }
    
    /* Phase 2: Try partial matching with word overlap */
    int best_match_count = 0;
    const char *best_answer = NULL;
    
    /* Count words in message */
    char msg_words[64][64];
    int word_count = 0;
    char *token = strtok(msg_clean, " \\t");
    while (token && word_count < 64) {
        if (strlen(token) > 2) {  /* Skip very short words */
            strncpy(msg_words[word_count], token, 63);
            msg_words[word_count][63] = '\\0';
            word_count++;
        }
        token = strtok(NULL, " \\t");
    }
    
    for (int i = 0; QA_LOOKUP[i][0]; i++) {
        const char *keyword = QA_LOOKUP[i][0];
        const char *answer = QA_LOOKUP[i][1];
        
        /* Count how many keyword words appear in message */
        char kw_words[16][64];
        int kw_word_count = 0;
        char kw_copy[512];
        strncpy(kw_copy, keyword, 511);
        kw_copy[511] = '\\0';
        
        char *kw_token = strtok(kw_copy, " \\t");
        while (kw_token && kw_word_count < 16) {
            if (strlen(kw_token) > 2) {
                strncpy(kw_words[kw_word_count], kw_token, 63);
                kw_words[kw_word_count][63] = '\\0';
                kw_word_count++;
            }
            kw_token = strtok(NULL, " \\t");
        }
        
        /* Count matches */
        int match_count = 0;
        for (int kw = 0; kw < kw_word_count; kw++) {
            for (int mw = 0; mw < word_count; mw++) {
                if (strstr(msg_words[mw], kw_words[kw]) || 
                    strstr(kw_words[kw], msg_words[mw])) {
                    match_count++;
                    break;
                }
            }
        }
        
        /* Update best match */
        if (match_count > best_match_count && match_count >= kw_word_count / 2) {
            best_match_count = match_count;
            best_answer = answer;
        }
    }
    
    if (best_answer)
        return best_answer;
    
    return NULL;
}
""")

def main():
    qa_pairs = parse_knowledge_base('/Users/kolibri/Desktop/kolibri-project/knowledge/knowledge_base_qa.md')
    
    print(f"/* Parsed {len(qa_pairs)} Q&A pairs from knowledge base */")
    print()
    
    # Generate lookup table with multiple keywords per entry
    generate_c_lookup_code(qa_pairs)
    print()
    
    # Generate improved matching function
    generate_improved_matcher(qa_pairs)

if __name__ == '__main__':
    main()
