#!/usr/bin/env python3
"""
Generate optimized QA_LOOKUP table from knowledge_base_qa.md
Creates a comprehensive lookup with smart keyword extraction
"""

import re

def parse_knowledge_base(filepath):
    """Parse knowledge_base_qa.md and extract Q&A pairs"""
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    entries = content.split('---\n')
    qa_pairs = []
    for entry in entries:
        entry = entry.strip()
        if not entry:
            continue
        
        match = re.match(r'### Q:\s*(.+?)\n\n\*\*Ответ:\*\*\s*(.+)', entry, re.DOTALL)
        if match:
            question = match.group(1).strip()
            answer = match.group(2).strip()
            qa_pairs.append((question, answer))
    
    return qa_pairs

def extract_best_keywords(question):
    """Extract the best keywords for matching - focus on unique, specific terms"""
    
    # Common stop words to remove
    stop_words = {
        'кто', 'что', 'какой', 'какая', 'какое', 'какие', 'сколько', 
        'где', 'когда', 'почему', 'зачем', 'как', 'каков',
        'у', 'в', 'во', 'на', 'с', 'со', 'по', 'о', 'об', 'от', 'до', 'из',
        'для', 'при', 'через', 'после', 'между', 'над', 'под',
        'и', 'или', 'но', 'а', 'же', 'ли', 'бы', 'не', 'ни', 'то',
        'это', 'тот', 'эта', 'эти', 'все', 'весь', 'всех',
        'самый', 'самая', 'самое', 'самые', 'более', 'меньше',
        'есть', 'был', 'была', 'были', 'будет', 'будут',
        'чем', 'чем-то', 'чем-нибудь', 'нибудь'
    }
    
    # Convert to lowercase
    question_lower = question.lower()
    
    # Remove punctuation except hyphens in words
    question_clean = re.sub(r'[?!,.;:()"]', '', question_lower)
    
    # Split into words
    words = question_clean.split()
    
    # Filter stop words and very short words
    important = [w for w in words if w not in stop_words and len(w) > 2]
    
    # Generate different types of keywords
    keywords = []
    
    # 1. Add 2-3 word phrases (most specific)
    if len(important) >= 2:
        for i in range(min(len(important) - 1, 3)):
            phrase = ' '.join(important[i:i+2])
            keywords.append(phrase)
    
    # 2. Add individual important words (longer ones first)
    important_sorted = sorted(important, key=len, reverse=True)
    keywords.extend(important_sorted[:5])
    
    # 3. Add truncated versions for fuzzy matching
    for word in important_sorted[:3]:
        if len(word) > 5:
            keywords.append(word[:-1])  # Remove last character
        if len(word) > 7:
            keywords.append(word[:-2])  # Remove last 2 characters
    
    # Remove duplicates while preserving order
    seen = set()
    unique = []
    for kw in keywords:
        if kw not in seen and len(kw) > 2:
            seen.add(kw)
            unique.append(kw)
    
    return unique[:8]  # Return top 8 keywords

def main():
    qa_pairs = parse_knowledge_base('/Users/kolibri/Desktop/kolibri-project/knowledge/knowledge_base_qa.md')
    
    print(f"/* Parsed {len(qa_pairs)} Q&A pairs from knowledge base */")
    print(f"/* Auto-generated by generate_qa_lookup.py - DO NOT EDIT */\n")
    
    # Collect all keyword->answer mappings
    keyword_to_answer = {}
    
    for question, answer in qa_pairs:
        keywords = extract_best_keywords(question)
        
        for kw in keywords:
            # Only add if not already mapped (avoid duplicates)
            if kw not in keyword_to_answer:
                keyword_to_answer[kw] = answer
    
    # Generate C array
    print("static const char *QA_LOOKUP[][2] = {")
    
    count = 0
    for kw, answer in keyword_to_answer.items():
        kw_escaped = kw.replace('"', '\\"')
        answer_escaped = answer.replace('"', '\\"')
        print(f'    {{"{kw_escaped}", "{answer_escaped}"}},')
        count += 1
    
    print(f"    {{NULL, NULL}}  /* {count} keyword entries */")
    print("};")

if __name__ == '__main__':
    main()
