"""FastAPI application that proxies chat prompts to an upstream LLM."""
from __future__ import annotations

from typing import Optional

import os

from fastapi import Depends, FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from .gpu_store import router as gpu_router
from .content_factory import router as factory_router
from .os_bridge import router as os_router
from .crawler import router as crawler_router
from .agent import router as agent_router
from .ai_chat import router as ai_router
from .ai_voice import router as ai_voice_router
from .ai_engine import pre_init_engine
from .swarm_sync import swarm_router
from .distributed_crawler import router as dist_crawler_router
from .delta_sync import router as delta_sync_router
from .archiver_service import create_archiver_router
from .cognition_api import router as cognition_router
from .concept_api import router as concept_router
from .auth import router as auth_router
from .rate_limiter import RateLimitMiddleware
from .health import router as health_router
from .knowledge_builder import router as knowledge_router
from .common import Settings, get_settings, InferenceRequest, perform_upstream_call


class HealthResponse(BaseModel):
    status: str = "ok"
    response_mode: str


class InferenceResponse(BaseModel):
    response: str = Field(description="Text generated by the LLM")
    provider: str = Field(description="Identifier of the upstream provider")
    latency_ms: Optional[float] = Field(default=None, description="End-to-end latency for the upstream call")


from contextlib import asynccontextmanager


@asynccontextmanager
async def lifespan(application: FastAPI):
    """Lifespan: предзагрузка AI-движка при старте."""
    import threading
    threading.Thread(target=pre_init_engine, daemon=True, name="engine-init").start()
    yield
    get_settings.cache_clear()


app = FastAPI(title="Kolibri AI backend", version="0.2.0", lifespan=lifespan)

# CORS: конфигурируемый список доменов (по умолчанию — только localhost)
_cors_origins = [
    o.strip()
    for o in os.environ.get(
        "KOLIBRI_CORS_ORIGINS",
        "http://localhost:3000,http://localhost:5173,http://localhost:8080",
    ).split(",")
    if o.strip()
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=_cors_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- Rate-limiter (после CORS, до роутеров) ---
app.add_middleware(RateLimitMiddleware)

app.include_router(gpu_router)
app.include_router(factory_router)
app.include_router(os_router)
app.include_router(crawler_router)
app.include_router(agent_router)
app.include_router(ai_router)
app.include_router(ai_voice_router)
app.include_router(swarm_router)
app.include_router(dist_crawler_router)
app.include_router(delta_sync_router)
app.include_router(create_archiver_router())
app.include_router(cognition_router)
app.include_router(concept_router)
app.include_router(auth_router)
app.include_router(health_router)
app.include_router(knowledge_router)


@app.get("/api/health", response_model=HealthResponse)
async def health(settings: Settings = Depends(get_settings)) -> HealthResponse:
    return HealthResponse(status="ok", response_mode=settings.response_mode)


@app.get("/api/knowledge/healthz", response_model=HealthResponse)
async def knowledge_health(settings: Settings = Depends(get_settings)) -> HealthResponse:
    return HealthResponse(status="ok", response_mode=settings.response_mode)


@app.post("/api/v1/infer", response_model=InferenceResponse)
async def infer(
    request: InferenceRequest,
    settings: Settings = Depends(get_settings),
) -> InferenceResponse:
    if settings.response_mode != "llm":
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="LLM mode is disabled",
        )

    text, latency_ms, provider = await perform_upstream_call(request, settings)
    return InferenceResponse(response=text, provider=provider, latency_ms=latency_ms)
